if (VGG16_CONFIG_SET)
    return()
 endif(VGG16_CONFIG_SET)
if (NOT PROJECT_NAME)
    message(WARNING "Project name is unset! This file should only be included after calling project(...)")
endif(NOT PROJECT_NAME)
cmake_minimum_required(VERSION 3.1)
set(VGG16_CONFIG_SET TRUE)
set(CMAKE_VERBOSE_MAKEFILE TRUE)
set(CMAKE_CXX_STANDARD 14)
set(CMAKE_CXX_FLAGS "${CMAKE_CXX_FLAGS} -Wall -W -Wno-unused-parameter")
if (IS_CMAKE_BUILD)
    list(APPEND CMAKE_PREFIX_PATH "/opt/ros/kinetic")
endif(IS_CMAKE_BUILD)
set(CMAKE_EXPORT_COMPILE_COMMANDS TRUE)
INCLUDE_DIRECTORIES(common)
if (CMAKE_BUILD_TYPE MATCHES "Debug")
    message(STATUS "Building ${PROJECT_NAME} with debug flag enabled.")
    add_definitions(-DVGG16_DEBUG)
endif(CMAKE_BUILD_TYPE MATCHES "Debug")
