#ifndef PARAMS_HPP
#define PARAMS_HPP


/* Interface parameters */
#define PORT_WIDTH_BYTE 16  //Data bus width to the PR region is 128 bits
#define SIZE_OF_FLOAT 4
/* General parameters  */
#define MAX_BATCH 16
#define MAX_LAYER (0x1 << 6)

#define BYTE_OFFSET_PARAMETERS 0
#define BYTE_SIZE_PARAMETERS_PER_LAYER (0x1 << 23)

#define BYTE_SIZE_ACTIVATION (0x1 << 29)
#define BYTE_OFFSET_ACTIVATION_A (MAX_LAYER * BYTE_SIZE_PARAMETERS_PER_LAYER)
#define BYTE_OFFSET_ACTIVATION_B (BYTE_OFFSET_ACTIVATION_A  + BYTE_SIZE_ACTIVATION)

/* Fully-connected layer related parameters*/
#define FC_MAX_INPUT_SIZE 25088
#define FC_MAX_OUTPUT_SIZE 4096
#define FC_MAX_WEIGHT_SIZE FC_MAX_INPUT_SIZE*FC_MAX_OUTPUT_SIZE

/* Convolution-layer and pooling related parameters*/
#define CONVPOOL_MAX_KERNEL_SIZE 3
#define CONVPOOL_MAX_INPUT_DIMS 512
#define CONVPOOL_MAX_OUTPUT_DIMS 512
#define CONVPOOL_MAX_INPUT_WIDTH 226
#define CONVPOOL_MAX_INPUT_HEIGHT 226
#define CONVPOOL_MAX_OUTPUT_WIDTH 224
#define CONVPOOL_MAX_OUTPUT_HEIGHT 224
#define CONVPOOL_MAX_CONV_INPUT CONVPOOL_MAX_INPUT_DIMS*CONVPOOL_MAX_INPUT_WIDTH*CONVPOOL_MAX_INPUT_HEIGHT
#define CONVPOOL_MAX_CONV_OUTPUT CONVPOOL_MAX_OUTPUT_DIMS*CONVPOOL_MAX_OUTPUT_WIDTH*CONVPOOL_MAX_OUTPUT_HEIGHT
#define CONVPOOL_MAX_WEIGHT_SIZE CONVPOOL_MAX_OUTPUT_DIMS*CONVPOOL_MAX_INPUT_DIMS*CONVPOOL_MAX_KERNEL_SIZE*CONVPOOL_MAX_KERNEL_SIZE

/* On-chip broadcast buffer parameters */
#define EXP_TILE_INPUT_CONV_X 2  //2^2 = 4
#define EXP_TILE_INPUT_CONV_Y 2  //2^2 = 4
#define EXP_TILE_INPUT_CONV_Z 2 //2^3 = 4
#define MASK_TILE_INPUT_CONV_X 0x3
#define MASK_TILE_INPUT_CONV_Y 0x3
#define MASK_TILE_INPUT_CONV_Z 0x3
#define NUM_TILE_INPUT_CONV_X (0X1 << EXP_TILE_INPUT_CONV_X) //2^2 = 4
#define NUM_TILE_INPUT_CONV_Y (0X1 << EXP_TILE_INPUT_CONV_Y) //2^2 = 4
#define NUM_TILE_INPUT_CONV_Z (0X1 << EXP_TILE_INPUT_CONV_Z) //2^2 = 4


#define NUM_TILE_BROADCAST 64 //2^(2+2+2)
#define EXP_DEPTH_INPUT_CONV_X 6
#define EXP_DEPTH_INPUT_CONV_Y 6
#define EXP_DEPTH_INPUT_CONV_Z 0
#define NUM_DEPTH_INPUT_CONV_X (0X1 << EXP_DEPTH_INPUT_CONV_X)
#define NUM_DEPTH_INPUT_CONV_Y (0X1 << EXP_DEPTH_INPUT_CONV_Y)
#define NUM_DEPTH_INPUT_CONV_Z (0X1 << EXP_DEPTH_INPUT_CONV_Z)

#define NUM_DEPTH_BROADCAST NUM_DEPTH_INPUT_CONV_X*NUM_DEPTH_INPUT_CONV_Y*NUM_DEPTH_INPUT_CONV_Z

#define NUM_INPUT_X 256
#define NUM_INPUT_Y 256
#define NUM_INPUT_Z 1

/* On-chip output buffer parameters */
/* On-chip broadcast buffer parameters */
#define EXP_TILE_OUTPUT_CONV_X 2  //2^2 = 4
#define EXP_TILE_OUTPUT_CONV_Y 2  //2^2 = 4
#define EXP_TILE_OUTPUT_CONV_Z 3 //2^3 = 8
#define MASK_TILE_OUTPUT_CONV_X 0x3
#define MASK_TILE_OUTPUT_CONV_Y 0x3
#define MASK_TILE_OUTPUT_CONV_Z 0x7
#define NUM_TILE_OUTPUT_CONV_X (0X1 << EXP_TILE_OUTPUT_CONV_X) //2^2 = 4
#define NUM_TILE_OUTPUT_CONV_Y (0X1 << EXP_TILE_OUTPUT_CONV_Y) //2^2 = 4
#define NUM_TILE_OUTPUT_CONV_Z (0X1 << EXP_TILE_OUTPUT_CONV_Z) //2^3 = 8

#define NUM_TILE_OUTPUT 128 //2^(2+2+3)
#define EXP_DEPTH_OUTPUT_CONV_X 6
#define EXP_DEPTH_OUTPUT_CONV_Y 6
#define EXP_DEPTH_OUTPUT_CONV_Z 0
#define NUM_DEPTH_OUTPUT_CONV_X (0X1 << EXP_DEPTH_OUTPUT_CONV_X)
#define NUM_DEPTH_OUTPUT_CONV_Y (0X1 << EXP_DEPTH_OUTPUT_CONV_Y)
#define NUM_DEPTH_OUTPUT_CONV_Z (0X1 << EXP_DEPTH_OUTPUT_CONV_Z)

#define NUM_DEPTH_OUTPUT NUM_DEPTH_OUTPUT_CONV_X*NUM_DEPTH_OUTPUT_CONV_Y*NUM_DEPTH_OUTPUT_CONV_Z

#define NUM_OUTPUT_X 256
#define NUM_OUTPUT_Y 256
#define NUM_OUTPUT_Z 8

/* On-chip weights buffer, computation buffer, and parallelization parameters
For VGG-16 ONLY!!!!*/
#define NUM_PARALLEL_X 3
#define NUM_PARALLEL_Y 3
#define NUM_PARALLEL_C 1
#define NUM_PARALLEL_K 4
#define NUM_PARALLEL_ONE_KERNEL (NUM_PARALLEL_C*NUM_PARALLEL_Y*NUM_PARALLEL_X)

#endif // PARAMS_HPP
