#ifndef PARAMS_HPP
#define PARAMS_HPP


/* Interface parameters */
#define PORT_WIDTH_BYTE 16  //Data bus width to the PR region is 128 bits

/* General parameters  */
#define MAX_BATCH 10

/* Fully-connected layer related parameters*/
#define FC_MAX_INPUT_SIZE 25088
#define FC_MAX_OUTPUT_SIZE 4096
#define FC_MAX_WEIGHT_SIZE FC_MAX_INPUT_SIZE*FC_MAX_OUTPUT_SIZE

/* Convolution-layer and pooling related parameters*/
#define CONVPOOL_MAX_KERNEL_SIZE 3
#define CONVPOOL_MAX_INPUT_DIMS 512
#define CONVPOOL_MAX_OUTPUT_DIMS 512
#define CONVPOOL_MAX_INPUT_WIDTH 226
#define CONVPOOL_MAX_INPUT_HEIGHT 226
#define CONVPOOL_MAX_OUTPUT_WIDTH 224
#define CONVPOOL_MAX_OUTPUT_HEIGHT 224
#define CONVPOOL_MAX_CONV_INPUT CONVPOOL_MAX_INPUT_DIMS*CONVPOOL_MAX_INPUT_WIDTH*CONVPOOL_MAX_INPUT_HEIGHT
#define CONVPOOL_MAX_CONV_OUTPUT CONVPOOL_MAX_OUTPUT_DIMS*CONVPOOL_MAX_OUTPUT_WIDTH*CONVPOOL_MAX_OUTPUT_HEIGHT
#define CONVPOOL_MAX_WEIGHT_SIZE CONVPOOL_MAX_OUTPUT_DIMS*CONVPOOL_MAX_INPUT_DIMS*CONVPOOL_MAX_KERNEL_SIZE*CONVPOOL_MAX_KERNEL_SIZE

/* On-chip broadcast buffer parameters */
#define EXP_TILE_INPUT_CONV_X 2  //2^2 = 4
#define EXP_TILE_INPUT_CONV_Y 2  //2^2 = 4
#define EXP_TILE_INPUT_CONV_Z 3 //2^3 = 8
#define MASK_TILE_INPUT_CONV_X 0x3
#define MASK_TILE_INPUT_CONV_Y 0x3
#define MASK_TILE_INPUT_CONV_Z 0x7

#define NUM_TILE_BROADCAST 128 //2^(2+2+3)
#define NUM_DEPTH_INPUT_CONV_X 64
#define NUM_DEPTH_INPUT_CONV_Y 64
#define NUM_DEPTH_INPUT_CONV_Z 1

#define NUM_DEPTH_BROADCAST NUM_DEPTH_INPUT_CONV_X*NUM_DEPTH_INPUT_CONV_Y*NUM_DEPTH_INPUT_CONV_Z

#endif // PARAMS_HPP
